# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: sqlite3
  encoding: unicode
  port: 5432
  username: postgres
  password: 1234
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: railsappdev # Set your development database name here

test:
  <<: *default
  database: railsapptest # Set your test database name here, not same with dev or prod

production:
  <<: *default
  database: railsapp # Set your production database name here
